### ISSUE TITLE
Ability to create cards

### ISSUE THREAD

**Issue by richardmable** [SethLieberman/Flash-Card-App#1]

**Comment by JonathanWexler** [comment]
Aside from a cards_controller, what other controllers should creating a card rely on?

**Comment by richardmable** [comment]
Creating a standard card relies on being an admin. Only admins can create the standard, pre-loaded cards and edit them. The idea is that since the content is based of the NYCDA curriculum, the content may change, or a card may have a mistake, etc. Then there will be user created cards, both public and private. Users can only create public cards once they have passed all the levels (basically the course).

**Comment by richardmable** [comment]
This is complete. The admins can now CRUD cards.
